apiVersion: v1
kind: Pod
metadata:
  name: getting-started
  labels:
    app: test  
spec:
  imagePullSecrets:
      - name:  my-skaffold-secret
  containers:
  - name: getting-started
    image: ghcr.io/seong7/skaffold-example
